changelog:
    sections:
        - title: 'New Features'
          labels: ['feature']
        - title: 'Bug-Fixes'
          labels: ['bug', 'regression']
        - title: 'Documentation Updates'
          labels: ['documentation']
        - title: 'Development Process Updates'
          labels: ['devops']
        - title: 'Dependency Upgrades'
          labels: ['dependencies']
        - title: 'Performance Improvements'
          labels: ['performance']
        - title: 'Code Health and Technical Debt'
          labels: ['maintainability', 'readability']
        - title: 'Enhancements'
          labels: ['enhancement']
        - title: 'Software Verification and Validation'
          labels: ['tests']
