name: Auto Merge

on:
    pull_request_target:
        types:
            - opened
            - synchronize

jobs:
    auto-merge:
        runs-on: ubuntu-latest
        steps:
            - name: Automerge Dependabot PRs
              uses: ahmadnassri/action-dependabot-auto-merge@v2
              with:
                  target: minor
                  merge-method: 'squash'
                  github-token: ${{ secrets.GITHUB_TOKEN }}
