name: Deploy to GitHub Pages

on:
    push:
        branches:
            - demo # Set this to the branch you want to trigger the deployment from.

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Enable Corepack
              run: corepack enable
            - name: Install and Build
              run: |
                  pnpm install
                  pnpm run build

            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v4
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./dist # Set this to the directory where your build script outputs the files.
