on: issues
name: Create Default Labels
jobs:
    labels:
        name: DefaultLabelsActions
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: lannonbr/issue-label-manager-action@4.0.0
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
