on:
    push:
        branches:
            - 'e/*'
            - 'f/*'
            - 'b/*'
            - 't/*'

permissions:
    pull-requests: write

jobs:
    pull-request:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Create or Edit Pull Request
              run: |
                  set -e
                  if ! gh pr create --title "${{ github.event.commits[0].message }}" --milestone 'next' --assignee 'ragaeeb' --draft false; then
                    gh pr edit --title "${{ github.event.commits[0].message }}" --milestone 'next' --assignee 'ragaeeb' --draft false
                  fi
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
